# Generated by Django 5.1.3 on 2026-09-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0004_rename_phone_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
